// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/career/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/career">> = Specific
  const handler = {} as typeof import("../../src/app/career/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/chamber/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chamber">> = Specific
  const handler = {} as typeof import("../../src/app/chamber/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cian-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cian-lab">> = Specific
  const handler = {} as typeof import("../../src/app/cian-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/command/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/command">> = Specific
  const handler = {} as typeof import("../../src/app/command/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/discovery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/discovery">> = Specific
  const handler = {} as typeof import("../../src/app/discovery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/exodus-academy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/exodus-academy">> = Specific
  const handler = {} as typeof import("../../src/app/exodus-academy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/heal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/heal">> = Specific
  const handler = {} as typeof import("../../src/app/heal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobseeker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobseeker">> = Specific
  const handler = {} as typeof import("../../src/app/jobseeker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing">> = Specific
  const handler = {} as typeof import("../../src/app/landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ledger/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ledger">> = Specific
  const handler = {} as typeof import("../../src/app/ledger/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/market-override/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/market-override">> = Specific
  const handler = {} as typeof import("../../src/app/market-override/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/merkaba/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/merkaba">> = Specific
  const handler = {} as typeof import("../../src/app/merkaba/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/movie/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/movie">> = Specific
  const handler = {} as typeof import("../../src/app/movie/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/neurodivergent-engine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/neurodivergent-engine">> = Specific
  const handler = {} as typeof import("../../src/app/neurodivergent-engine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/podcast/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/podcast">> = Specific
  const handler = {} as typeof import("../../src/app/podcast/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/quantum-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quantum-lab">> = Specific
  const handler = {} as typeof import("../../src/app/quantum-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/shield/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shield">> = Specific
  const handler = {} as typeof import("../../src/app/shield/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/spatial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/spatial">> = Specific
  const handler = {} as typeof import("../../src/app/spatial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/wormhole/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wormhole">> = Specific
  const handler = {} as typeof import("../../src/app/wormhole/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai-chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai-chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/analyze-resume/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analyze-resume">> = Specific
  const handler = {} as typeof import("../../src/app/api/analyze-resume/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/find-jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/find-jobs">> = Specific
  const handler = {} as typeof import("../../src/app/api/find-jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/helmet/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/helmet">> = Specific
  const handler = {} as typeof import("../../src/app/api/helmet/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ledger-grounding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ledger-grounding">> = Specific
  const handler = {} as typeof import("../../src/app/api/ledger-grounding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/resonance-loop/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resonance-loop">> = Specific
  const handler = {} as typeof import("../../src/app/api/resonance-loop/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sovereign-interview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sovereign-interview">> = Specific
  const handler = {} as typeof import("../../src/app/api/sovereign-interview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
